In [3]:
import numpy as np
import matplotlib.pyplot as plt
import copy
import math
%matplotlib inline
import pandas as pd



In [4]:
import pandas as pd
import numpy as np

# Create the dataset
data = {
    'Size_sqft': [2104, 1600, 2400, 1416, 3000, 1985, 1534, 1427, 1380, 1494],
    'Bedrooms': [3, 3, 3, 2, 4, 4, 3, 3, 3, 3],
    'Age': [15, 20, 10, 25, 8, 12, 30, 20, 18, 24],
    'Distance_km': [5.0, 6.5, 4.0, 8.0, 3.5, 4.2, 6.0, 5.5, 7.0, 7.5],
    'Price_k': [400, 330, 369, 232, 540, 400, 315, 280, 275, 299]
}

# Load into a DataFrame
df = pd.DataFrame(data)

# Split into features (X) and target (y)
X = df[['Size_sqft', 'Bedrooms', 'Age', 'Distance_km']].values
y = df['Price_k'].values

# Preview
print("Features (X):")
print(X, type(X))
print("\nTarget (y):")
print(y, type(y))


Features (X):
[[2.104e+03 3.000e+00 1.500e+01 5.000e+00]
 [1.600e+03 3.000e+00 2.000e+01 6.500e+00]
 [2.400e+03 3.000e+00 1.000e+01 4.000e+00]
 [1.416e+03 2.000e+00 2.500e+01 8.000e+00]
 [3.000e+03 4.000e+00 8.000e+00 3.500e+00]
 [1.985e+03 4.000e+00 1.200e+01 4.200e+00]
 [1.534e+03 3.000e+00 3.000e+01 6.000e+00]
 [1.427e+03 3.000e+00 2.000e+01 5.500e+00]
 [1.380e+03 3.000e+00 1.800e+01 7.000e+00]
 [1.494e+03 3.000e+00 2.400e+01 7.500e+00]] <class 'numpy.ndarray'>

Target (y):
[400 330 369 232 540 400 315 280 275 299] <class 'numpy.ndarray'>


Predict


In [5]:
def predict(w, x, b):

    return np.dot(w, x)+b

Cost Function

In [6]:
def get_cost(w, x, y, b):

    n=len(w)
    cost=0

    for i in range(n):
        f_wb_i= np.dot(x[i], w)+b
        cost=cost+(y[i]-f_wb_i)**2
    
    cost=cst/(2*m)
    return cost


Compute Gradient

In [8]:
def get_gradient(w, b, x, y):

    m=len(x)
    n=len(x[0])

    dj_dw= np.zeroes(n)
    dj_db=0

    for i in range(m):

        err=np.dot(x[i], w)+b-y[i]

        for j in range(n):

            dj_dw[j]=dj_dw[j]+err*x[i, j]
        dj_db=dj_db+err

    dj_dw=dj_dw/m
    dj_db=dj_db/m

In [ ]:
def gradient_descent(w, b, x,y):
    